project:
  type: website

website:
  title: "Jiaqi Cheng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Example Analysis.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

